[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"
author = "Wakeland Branz"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
